### ISSUE TITLE
eslintの内容を拡充する

### ISSUE THREAD

**Issue by mesh1nek0x0** [mesh1nek0x0/node-lambda-starter-kit#8]
#7 での追加対応予定

NOTE
ESLintのエラールール。日本語ざっくり解説[可能性あるエラー編]
https://qiita.com/M-ISO/items/f9097a75b362206c2a99

必要そうなものをpickして適用する

**Comment by keitakn** [comment]
既に考慮済かもしれませんが、ESLintに関してはPrettierと合わせて利用するのがデファクトスタンダートとなりつつあります。

詳しい設定内容に関しては下記をご覧下さい。

- https://qiita.com/soarflat/items/06377f3b96964964a65d
- http://tech-1natsu.hatenablog.com/entry/2018/01/07/154941

これは個人的な見解も含まれますが、基本ルールを自分で設定すると個人の好みの違いが出てくるので、Prettier等のルールに合わせるのが良いと感じています。

参考になれば幸いです。

**Comment by mesh1neko** [comment]
@keitakn ありがとうございます！Prettierは名前だけ聞いたことあったのですが、これを機に導入してみようと思います ✨ いつもアドバイスありがとうございます！勉強になります 📝

**Comment by mesh1neko** [comment]
memo
書き方がよくないのかyamlだとpretterの内容が反映されていないもよう。jsonに書き換えて再チャレンジ

**Comment by mesh1neko** [comment]
JSONで書いたらうまく動作した。
![image](https://user-images.githubusercontent.com/10177370/40572180-6dd254cc-60e0-11e8-9351-d3b19d0ff374.png)

yamlにこだわりはないので、こちらで

**Comment by mesh1nek0x0** [comment]
#13 にてprettierを導入完了、引き続きeslintの項目を精査する

**Comment by mesh1nek0x0** [comment]
https://eslint.org/docs/rules/
こちらのPossible Errorsの項目で

> eslint:recommended

に含まれないものを検討する

**Comment by mesh1nek0x0** [comment]
バグにつながりそうなものや、書き方ぶれそうなものについて
統一できるようにルールを検討した。

## Possible Errors
* no-await-in-loop
* no-template-curly-in-string
* valid-jsdoc

## Best Practices
* eqeqeq
* curly
* no-magic-numbers
* no-return-await

## Node.js and CommonJS
なし

## Stylistic Issues
これはPrettierに移譲

## ECMAScript 6
なし

**Comment by mesh1nek0x0** [comment]
エラーになることを確認した
![image](https://user-images.githubusercontent.com/10177370/40584184-147f9814-61d8-11e8-91a9-f91d1f68c5f4.png)

**Comment by mesh1nek0x0** [comment]
#14 にて対応done
